# Generated by Django 5.2 on 2025-05-18 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_answer_is_anonymous_feedback_is_anonymous'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='allow_anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
